obj-$(CONFIG_DEBUG_INTERRUPT0)      += interrupt0.o
obj-$(CONFIG_DEBUG_DIVIDE_ZERO)     += divi_zero.o
obj-$(CONFIG_DEBUG_OVERFLOW_BIT)    += over_destination.o
obj-$(CONFIG_DEBUG_SOFT_INT0)       += soft-interrupt.o
