# ----------------------------------------------------------------------
# Qemu option
# Maintainer: Buddy <buddy.zhang@aliyun.com>
#
# Copyright (C) 2017 BiscuitOS
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

# -----------------------------------
# Qemu flags
# -----------------------------------
QEMU_FLAGS :=

# -----------------------------------
# Platform
# -----------------------------------
ifeq ($(ARCH), x86)
QEMU := qemu-system-x86_64
else
QEMU := qemu
endif

# -----------------------------------
# Boot from
# -----------------------------------
BOOTLOADER := Floppy
#BOOTLOADER := Disk

# -----------------------------------
# Image File
# -----------------------------------
IMAGE_FILE := BiscuitOS.img

# -----------------------------------
# Memory size
# -----------------------------------
MEMORY_SIZE := 16M
QEMU_FLAGS  += -m $(MEMORY_SIZE)

# -----------------------------------
# Boot order
# On X86 machine
# a: floppy 1
# b: floppy 2
# c: first hard disk
# d: first CD-ROM
# n: Etherboot from network adapter 1
# o: Etherboot from network adapter 2
# p: Etherboot from network adapter 3
# q: Etherboot from network adapter 4
# Hard disk boot is the default
# -----------------------------------
ifeq ($(BOOTLOADER), Floppy)
  BOOT_DEVICE := a
else
  BOOT_DEVICE := c
endif
QEMU_FLAGS += -boot order=$(BOOT_DEVICE)

# -----------------------------------
# Virtual device
# -----------------------------------
ifeq ($(BOOTLOADER), Floppy)
  VIRTUAL_DEVICE := /dev/loop0
else
  VIRTUAL_DEVICE :=
endif

# -----------------------------------
# Block device options
# Utilize file as block
# For floppy:
# -fda : floppy disk 0 image
# -fdb : floppy disk 1 image
# For Disk:
# -hda : hard disk 0 image
# -hdb : hard disk 1 image
# -hdc : hard disk 2 image
# -hdd : hard disk 3 image
# -----------------------------------
ifeq ($(BOOTLOADER), Floppy)
  BLOCK_DEVICE := -fda Image
else
  BLOCK_DEVICE := -fda Image
endif
QEMU_FLAGS += $(BLOCK_DEVICE)

# -----------------------------------
# Rootfs
# -----------------------------------
ROOTFS := -hda BiscuitOS.img

#QEMU_FLAGS += $(ROOTFS)

# -----------------------------------
# Display options
# -----------------------------------
CONS :=
QEMU_FLAGS += $(CONS)

# -----------------------------------
# Real Time Chip(RTC)
# -----------------------------------
# Specify time
# RTC := -rtc base=2017-10-16T16:01:21
# Local time
RTC := -rtc base=localtime
# UTL time (default)
# RTC := -rtc base=utc
QEMU_FLAGS += $(RTC)


# ----------------------------------
# Serial Settings
# ----------------------------------
SERIAL := -serial pty

QEMU_FLAGS += $(SERIAL)
# Export Argument
export QEMU_FLAGS QEMU

