obj-$(CONFIG_DEBUG_MMU_VA)         += virtual_address/
obj-$(CONFIG_DEBUG_MMU_LA)         += logical_address/
obj-$(CONFIG_DEBUG_MMU_SEGMENT)    += segment/
obj-$(CONFIG_DEBUG_MMU_PAGING)     += paging/
