obj-$(CONFIG_DEBUG_SYSCALL)       += syscall.o
obj-$(CONFIG_DEBUG_POSIX_SETUP)   += setup/
obj-$(CONFIG_DEBUG_POSIX_OPEN)    += open/
obj-$(CONFIG_DEBUG_POSIX_READ)    += read/
obj-$(CONFIG_DEBUG_POSIX_WRITE)   += write/
obj-$(CONFIG_DEBUG_POSIX_CLOSE)   += close/
