# ----------------------------------------------------------------------
# Debug option
# Maintainer: Buddy <buddy.zhang@aliyun.com>
#
# Copyright (C) 2017 BiscuitOS
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

# -----------------------------------
# Debug tools
# -----------------------------------

ifdef CONFIG_QEMU
  include $(srctree)/tools/debug/qemu/Makefile
endif
