obj-$(CONFIG_TESTCASE_SCHED)       += common.o
obj-$(CONFIG_TESTCASE_GDT)         += gdt/
obj-$(CONFIG_TESTCASE_SEGMENT)     += segment/
obj-$(CONFIG_TESTCASE_GATE)        += gate/
obj-$(CONFIG_TESTCASE_IDT)         += idt/
obj-$(CONFIG_TESTCASE_STACK)       += stack/
