obj-$(CONFIG_DEBUG_SCHED)             += common.o
obj-$(CONFIG_DEBUG_GDT)               += gdt/
obj-$(CONFIG_DEBUG_SEGMENT)           += segment/
obj-$(CONFIG_DEBUG_GATE)              += gate/
obj-$(CONFIG_DEBUG_IDT)               += idt/
obj-$(CONFIG_DEBUG_STACK)             += stack/
obj-$(CONFIG_DEBUG_TASK)              += task/
