obj-$(CONFIG_DEBUG_VFS_INODE)       += inode/
obj-$(CONFIG_DEBUG_VFS_FILE_TABLE)  += file_table/
obj-$(CONFIG_DEBUG_VFS_SUPER)       += super/
obj-$(CONFIG_DEBUG_VFS_NAMEI)       += namei/
obj-$(CONFIG_DEBUG_VFS_BUFFER)      += buffer/
