obj-$(CONFIG_DEBUG_SYSCALL)                += common.o
obj-$(CONFIG_DEBUG_SYSCALL_ROUTINE)        += system.o
obj-$(CONFIG_DEBUG_SYSCALL_OPEN)           += open/
obj-$(CONFIG_DEBUG_SYSCALL_CLOSE)          += close/
obj-$(CONFIG_DEBUG_SYSCALL_READ)           += read/
obj-$(CONFIG_DEBUG_SYSCALL_WRITE)          += write/
obj-$(CONFIG_DEBUG_SYSCALL_DUP)            += dup/
