obj-$(CONFIG_DEBUG_MMU)                += common.o
obj-$(CONFIG_DEBUG_MMU_LINEAR)         += linear/
obj-$(CONFIG_DEBUG_MMU_PHYSIC)         += physic/
obj-$(CONFIG_DEBUG_MMU_VIRTUAL)        += virtual/
obj-$(CONFIG_DEBUG_MMU_LOGIC)          += logic/
obj-$(CONFIG_DEBUG_MMU_PGTABLE)        += pgtable/
obj-$(CONFIG_DEBUG_MMU_SEGMENTATION)   += segmentation/
