obj-$(CONFIG_DEBUG_BLOCK_HD)                += common.o
obj-$(CONFIG_DEBUG_BLOCK_HD_DEV)            += hd.o
obj-$(CONFIG_DEBUG_BLOCK_HD_INT)            += interrupt.o
obj-$(CONFIG_DEBUG_BLOCK_HD_USAGE)          += usage.o
