obj-$(CONFIG_DEBUG_BLOCK_DEV)                += common.o
obj-$(CONFIG_DEBUG_BLOCK_HD)                 += hard-disk/
obj-$(CONFIG_DEBUG_DISK_CHS)                 += CHS/
obj-$(CONFIG_DEBUG_DISK_PARTITION)           += partition/
