lib-$(CONFIG_DEBUG_SYSCALL_OPEN0)      += d_open.o
lib-$(CONFIG_DEBUG_SYSCALL_CLOSE0)     += d_close.o
lib-$(CONFIG_DEBUG_SYSCALL_READ0)      += d_read.o
lib-$(CONFIG_DEBUG_SYSCALL_WRITE0)     += d_write.o
lib-$(CONFIG_DEBUG_SYSCALL_DUP0)       += d_dup.o
lib-$(CONFIG_DEBUG_SYSCALL_EXECVE0)    += d_execve.o
lib-$(CONFIG_DEBUG_SYSCALL_STACK)      += d_stack.o

