obj-$(CONFIG_TESTCASE)            += common.o
obj-$(CONFIG_TESTCASE_IDT)        += interrupt/
obj-$(CONFIG_TESTCASE_ASSEMBLY)   += assembly/
obj-$(CONFIG_TESTCASE_SCHED)      += scheduler/
obj-$(CONFIG_TESTCASE_MMU)        += mmu/
