obj-$(CONFIG_TESTCASE)            += common.o
obj-$(CONFIG_TESTCASE_INTERRUPT)  += interrupt/
obj-$(CONFIG_TESTCASE_ASSEMBLY)   += assembly/
obj-$(CONFIG_TESTCASE_SCHED)      += scheduler/
obj-$(CONFIG_TESTCASE_MMU)        += mmu/
obj-$(CONFIG_TESTCASE_TIMER)      += timer/
obj-$(CONFIG_TESTCASE_IOPORT)     += ioports/
obj-$(CONFIG_TESTCASE_SYSCALL)    += systemcall/
