obj-$(CONFIG_DEBUG_INTERRUPT5)      += interrupt5.o
obj-$(CONFIG_DEBUG_SOFT_INT5)       += soft-interrupt.o
obj-$(CONFIG_DEBUG_INT5_BOUND)      += bound-interrupt.o
obj-$(CONFIG_DEBUG_INT5_BNDCL)      += bndcl-interrupt.o
obj-$(CONFIG_DEBUG_INT5_BNDCU)      += bndcu-interrupt.o
