obj-$(CONFIG_MINIX_FS) += bitmap.o
obj-$(CONFIG_MINIX_FS) += inode.o
obj-$(CONFIG_MINIX_FS) += namei.o
obj-$(CONFIG_MINIX_FS) += truncate.o
obj-$(CONFIG_MINIX_FS) += dir.o
obj-$(CONFIG_MINIX_FS) += file.o
obj-$(CONFIG_MINIX_FS) += symlink.o
obj-$(CONFIG_MINIX_FS) += fsync.o
