obj-$(CONFIG_DEMO_CODE)            += core.o
obj-$(CONFIG_DEBUG_MMU)            += mmu/
obj-$(CONFIG_DEBUG_VFS)            += vfs/
obj-$(CONFIG_DEBUG_POSIX)          += posix/
obj-$(CONFIG_DEBUG_DDL)            += drivers/
obj-$(CONFIG_DEBUG_DATA)           += Data/
