obj-$(CONFIG_DEBUG_INTERRUPT)       += common.o
obj-$(CONFIG_DEBUG_INT_USAGE)       += interrupt.o
obj-$(CONFIG_DEBUG_IDT)             += idt/
obj-$(CONFIG_DEBUG_INTERRUPT0)      += interrupt0/
obj-$(CONFIG_DEBUG_INTERRUPT1)      += interrupt1/
