obj-$(CONFIG_FS_EXT) += dir.o
obj-$(CONFIG_FS_EXT) += file.o
obj-$(CONFIG_FS_EXT) += freelists.o
obj-$(CONFIG_FS_EXT) += inode.o
obj-$(CONFIG_FS_EXT) += namei.o
obj-$(CONFIG_FS_EXT) += symlink.o
obj-$(CONFIG_FS_EXT) += truncate.o
obj-$(CONFIG_FS_EXT) += fsync.o
