obj-$(CONFIG_DEBUG_SEGMENT_FS)               += common.o
obj-$(CONFIG_DEBUG_SEGMENT_FS)               += syscall.o
obj-$(CONFIG_DEBUG_SEGMENT_OBTAIN_USERLAND)  += userland.o
obj-$(CONFIG_DEBUG_SEGMENT_PUSH_KERNEL)      += kernel.o
