/*
 * interrupt 3: Breakpoint
 *
 * (C) 2017.10 <buddy.zhang@aliyun.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */
#include <linux/kernel.h>

/*
 * Test Interrupt 3 - int3 
 * Breakpoint Interrupt If you have used a debugger, which you should
 * have by now, you already know the usefulness of inserting breakpoints
 * while debugging a program. The type 3 interrupt is dedicated to the 
 * breakpoint processing. This type of interrupt can be generated by 
 * using the special single-byte form of 'int3' (opcode CCH). Using the
 * 'int3' instruction automatically causes the assembler to encode the 
 * instruction into the single-byte version. Note that the standard encoding
 * for the 'int' instruction is two bytes long.
 * Inserting a breakpoint in a program involves replacing the program 
 * code byte by CCH while saving the program byte for later restoration
 * to remove the breakpoint. The standard 2-byte version of 'int3' can 
 * cause problems in certain situations, as there are instructions that 
 * require only a single byte to encode.
 */

/* trigger interrupt by set TF(Trap flag) bit on EFLAGS */
//#define INT3_SET_TF       0x01

/* trigger interrupt by soft-interrup */
#define INT3_SOFTINT      0x02

/* trigger interrupt 3: set TF bit 
 * When TF on EFLAGS is set, the system will trigger interrupt 3,
 * this interrupt is named 'break point'.
 */
#ifdef INT3_SET_TF
void trigger_interrupt3(void)
{
    printk("Test interrupt 3: Set TF bit on EFLAGS.\n");
    /* general interrupt entry */
    __asm__ ("pushl %%eax\n\t"
             "pushf\n\t"
             "movl %%esp, %%eax\n\t"
             "orl $0x0100, (%%eax)\n\t"
             "popf\n\t"
             "popl %%eax"
             ::);
}
#endif

/*
 * Trigger interrupt 3: invoke 'int $0x03'
 * The interrupt 3 must be triggered by invoking 'int $0x03'.
 * Note! This routine will be trigger whatever interrupt is 
 * enable or disable.
 */
#ifdef INT3_SOFTINT
void trigger_interrupt3(void)
{
    printk("Test interrupt 3: invoke 'int $0x3'\n");
    __asm__ ("int $0x03");
}
#endif
